build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25

style:
  MaxLineLength:
    maxLineLength: 120
  UnusedPrivateMember:
    allowedNames: "_.*"
  MagicNumber:
    active: false
  ReturnCount:
    max: 4

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
